name: CI Build
on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  APP_NAME: "brew-gem"
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: '1'

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake
